name: Build and Push Docker Image

on:
  push:
    branches:
      - main      # Producción
      - staging   # Staging
      - develop   # Desarrollo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install

    - name: Build the TypeScript app
      run: yarn build

    - name: Build the Docker image
      run: docker build -t vvelc/nb-api-proto:${{ github.ref }}-latest .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push vvelc/nb-api-proto:${{ github.ref }}-latest

    - name: Tag the Docker image
      run: docker tag vvelc/nb-api-proto:${{ github.ref }}-latest vvelc/nb-api-proto:${{ github.ref }}-latest

    - name: Push latest tag
      run: docker push vvelc/nb-api-proto:${{ github.ref }}-latest
